# GitHub Pages Configuration
title: "Technical Documentation"
description: "Technical documentation / Architectural Overview"
baseurl: "/corefinder"
url: "https://corefinder89.github.io"

# Use logo file
logo: "/assets/image/logo.svg"

# Documentation Theme
remote_theme: pmarsceill/just-the-docs

# Basic settings
markdown: kramdown
highlighter: rouge

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
aux_links:
  "View on GitHub":
    - "https://github.com/Corefinder89/corefinder"

# Search
search_enabled: true

# Footer
footer_content: "Copyright &copy; 2025 Soumyajit Basu"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/