name: Generate Changelog

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.2.7)'
        required: true
        default: 'v1.2.7'
        type: string
  repository_dispatch:
    types: [changelog-update]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          
      - name: Determine trigger context
        id: context
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "commit_msg=Update changelog for ${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "commit_msg=Update changelog for ${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "version=PR-${{ github.event.number }}" >> $GITHUB_OUTPUT
            echo "commit_msg=Update changelog for PR #${{ github.event.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "version=${{ github.event.client_payload.version || 'latest' }}" >> $GITHUB_OUTPUT
            echo "commit_msg=Update changelog via repository dispatch" >> $GITHUB_OUTPUT
          else
            echo "version=unknown" >> $GITHUB_OUTPUT
            echo "commit_msg=Update changelog" >> $GITHUB_OUTPUT
          fi

      - name: Commit changelog
        run: |
          git config --local user.email "soumyajit.basu1988@outlook.com"
          git config --local user.name "Corefinder89"
          git add CHANGELOG.md
          git commit -m "${{ steps.context.outputs.commit_msg }}" || exit 0
          git push